name: gvxr-tutorials
channels:
    - conda-forge
    - https://software.repos.intel.com/python/conda
    - ccpi
    - pytorch
    - nvidia
dependencies:
    - python=3.11
    - numpy
    - pandas
    - matplotlib
    - ipyevents
    - ipympl
    - ipywidgets
    - jupyterlab
    - mpl-interactions
    - SimpleITK
    - cil
    - ccpi-regulariser
    - astra-toolbox=*=cuda*
    - tigre
    - progressbar
    - k3d
#    - python-dotenv
#    - pytorch-cuda
#    - torchvision
    - keras
    - protobuf
    - tensorflow-gpu
    - fsspec
#    - opencv
    - pip
    - pip:
        - "gvxr==2.1.0"
        - opengate
        - viewscad
        - segmentation-models
